<a href="https://colab.research.google.com/github/anhquan093/the-c-programming-language-2nd-edition-solutions/blob/main/Lab_2_Knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import statistics as st

In [ ]:
features = np.array([[1,     2], 
                    [1.5, 2.9], 
                    [1.3, 2.2], 
                    [1.6,   3], 
                    [1.8, 3.5], 
                    [1.9, 2.5]])

labels = np.array([[1],
                   [1],
                   [1],
                   [2],
                   [2],
                   [2]])

X = np.array([[1.4, 2.5]])

print(features)
print(labels)

[[1.  2. ]
 [1.5 2.9]
 [1.3 2.2]
 [1.6 3. ]
 [1.8 3.5]
 [1.9 2.5]]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]


In [ ]:
print(features[:,0])

[1.  1.5 1.3 1.6 1.8 1.9]


In [ ]:
# Standardization 

#Calculate the mean and variance of feature x1
mean_x1 = np.mean(features[:, 0])
var_x1 = np.var(features[:, 0])


#Calculate the mean and variance of feature x2
mean_x2 = np.mean(features[:, 1])
var_x2 = np.var(features[:, 1])


print("Mean of feature x1: ", mean_x1)
print("Variance of feature x1: ", var_x1)
print("\n")
print("Mean of feature x2: ", mean_x2)
print("Variance of feature x2: ", var_x2)

Mean of feature x1:  1.5166666666666666
Variance of feature x1:  0.0913888888888889


Mean of feature x2:  2.6833333333333336
Variance of feature x2:  0.25805555555555554


In [ ]:
# Standardize the given features

stand_features = features.copy()
stand_features[:, 0] = (features[:, 0].copy() - mean_x1) / np.sqrt(var_x1)

stand_features[:, 1] = (features[:, 1].copy() - mean_x2) / np.sqrt(var_x2)

print(stand_features)

[[-1.70908532 -1.34516637]
 [-0.05513178  0.42651616]
 [-0.7167132  -0.95145914]
 [ 0.27565892  0.62336978]
 [ 0.93724034  1.60763785]
 [ 1.26803105 -0.36089829]]


In [ ]:
# Standardize the features of X
stand_X = X.copy()
stand_X[:, 0] = (X[:, 0].copy() - mean_x1) / np.sqrt(var_x1)
stand_X[:, 1] = (X[:, 1].copy() - mean_x2) / np.sqrt(var_x2)

print(stand_X)

[[-0.38592249 -0.36089829]]


In [ ]:
# Calculate the features distance from 𝑋 to the data samples
d1 = stand_X.copy() - stand_features.copy() 
d2 = np.sqrt((d1[:, 0].copy()) ** 2  + (d1[:, 1].copy()) ** 2)

print(d1)
print(d2)


[[ 1.32316283  0.98426807]
 [-0.33079071 -0.78741446]
 [ 0.33079071  0.59056084]
 [-0.66158142 -0.98426807]
 [-1.32316283 -1.96853614]
 [-1.65395354  0.        ]]
[1.64910385 0.85407495 0.67689335 1.1859484  2.3718968  1.65395354]


In [ ]:
# Classification
# Choosing k for classification
k = 3
min_d = d2.argsort()[:k]

classify = labels[min_d] #extract the corresponding labels
print(classify)

# Find the mode label
print("Conclusion: X belongs to Label ", st.mode(classify[:,0]))

[[1]
 [1]
 [2]]
Conclusion: X belongs to Label  1
